from functions import *

grammar = {
    "persist": " fs",
    "persists": " fs",
    "process": " fs",
    "processed": " fs",
    "shell": "shell",
    "shelf": "shell",
    "cell": "shell",
    "sell": "shell",
    "show": "shell",
    "she'll": "shell",
    "shall": "shell",
    "okay": "fd",
    "switch": " bb",
    "search": " ss",
    "lip": " ww",
    "flip": " ww",
    "slip": " ww",
    "flick": " ww",
    "viewing": " bv",
    "helm": " :",
    "home": " :",
    "reload": ":e!",
    "compile": " cC<enter>",
    "status": " gs",
    "difference": " gd",
    "committing": " gh"
}
