grammar_filter = {
    # NOTE: Keys containing hyphens are used to correct mistakes where multiple
    #       words get mapped to a single incorrect word. This is a work around
    #       since grammar rule keys can only be single words.

    "two": ["two", "to"],
    "four": ["four", "for", "fore"],
    "a": ["hey", "pay"],
    "addition": ["edition"],
    "albert": ["alpert", "alberts", "albert's"],
    "alvin": ["album"],
    "append": ["uphend"],
    "array": ["parade", "hooray", "rate"],
    "b": ["be", "bee"],
    "bill-bill": ["billville"],
    "brace": ["bruce"],
    "c": ["see"],
    "camel": ["kamel"],
    "caret": ["carrot", "garret", "garrett"],
    "carl": ["karl"],
    "carol": ["carrol", "caroll", "carroll", "karol"],
    "case": ["base", "ace"],
    "cc": ["cici"],
    "clap": ["club", "clapp", "clop"],
    "commit": ["khemet"],
    "curly": ["early", "girly", "girlie", "currently"],
    "daniel-bill": ["danielville"],
    "dd": ["didi", "dede"],
    "dillan": ["dylan"],
    "down": ["dumb"],
    "down-down": ["countdown", "downtown"],
    "e": ["eat"],
    "eddie": ["eddy"],
    "find": ["fine", "fun"],
    "find-nancy": ["financing"],
    "finish": ["finished", "finnish"],
    "flip": ["lip", "flipped", "slip", "flick", "foot", "clip"],
    "flower": ["flour"],
    "gary": ["carry", "kerry", "garry", "gerry"],
    "gg": ["gigi", "gege"],
    "grammar": ["grammer", "grandma", "rammer"],
    "i": ["hi", "by", "bye", "high", "height", "eye"],
    "import": ["imports"],
    "increment": ["increments"],
    "initialize": ["initialized"],
    "jagger": ["jagar", "jager", "jagr"],
    "jeffrey": ["jefferey"],
    "length": ["links"],
    "lexer": ["lexor", "flexor"],
    "loop": ["luke"],
    "lower": ["blower", "lover", "over", "slower", "lowered"],
    "n": ["in"],
    "nose": ["knows"],
    "o": ["oh"],
    "orbit": ["dorbett"],
    "oscar": ["hosker"],
    "persist": ["persyst", "processed", "process", "persists", "persis"],
    "pound": ["found"],
    "print": ["prints"],
    "python": ["iphone"],
    "quillan": ["quillen", "quillian"],
    "quit": ["quick"],
    "quit": ["quits", "quick"],
    "quote": ["quotes"],
    "r": ["are"],
    "right": ["wright", "bright", "write", "writes", "rights", "rite"],
    "say": ["saying"],
    "scan": ["scam"],
    "shell": ["she'll", "shelf", "shall", "cell", "sell", "show"],
    "slap": ["slapped", "slop", "slot", "slut", "slept"],
    "smack": ["snack", "mac"],
    "smudge": ["smudged", "spuds", "smutz"],
    "spell": ["spelled", "spelt"],
    "steven": ["stephen"],
    "string": ["strain", "strained", "stream", "strength", "street"],
    "switch": ["switched"],
    "top": ["talk"],
    "trace": ["trees", "treece"],
    "turn": ["turned"],
    "u": ["you"],
    "ultimate": ["alternate"],
    "undo": ["undue", "under"],
    "vacs": ["fax", "backs"],
    "valerie": ["valery"],
    "viewing": ["feeling"],
    "visible": ["visual"],
    "y": ["why", "wife"],
    "yy": ["waiwai", "huewai"],
    "zebra": ["sibra", "seabrook"]
}
