grammar = {
    "alias": "alias",
    "aliases": "aliases",
    "compiler": "compiler",
    "config": "config",
    "control": "<lbracket>ctrl<rbracket>",
    "directory": "directory",
    "filter": "filter",
    "functions": "functions",
    "general": "general",
    "grammar": "grammar",
    "interpreter": "interpreter",
    "lexer": "lexer",
    "mode": "mode",
    "parser": "parser",
    "symbol": "symbol",
    "token": "token",
    "utilities": "utilities",
    "vacs": "vacs"
}
